spring: 
    profiles:
        active: dev
        
---
server:
  port: 8001

mybatis:
  type-aliases-package: com.tz.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  profiles: dev
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/
  instance: 
    instance-id: springcloud-provider-dept8001  #修改eureka上的默认描述
    prefer-ip-address: true    #访问路径可以显示IP地址
    
info: 
  app.name: com.tz.springcloud
  company.name: blog.tzStudy.com

---
server:
  port: 8001

mybatis:
  type-aliases-package: com.tz.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  profiles: test
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/
  instance: 
    instance-id: springcloud-provider-dept8001  #修改eureka上的默认描述
    prefer-ip-address: true    #访问路径可以显示IP地址
    
info: 
  app.name: com.tz.springcloud
  company.name: blog.tzStudy.com
        

